<a href="https://colab.research.google.com/github/Aaksha-sharma/SVM/blob/main/HandwrittendigitsSVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.datasets import load_digits
digits=load_digits()

In [5]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [7]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [10]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
df = pd.DataFrame(digits.data,digits.target)
df.head()

0    1    2     3     4     5    6   ...   57   58    59    60    61   62   63
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  ...  0.0  6.0  13.0  10.0   0.0  0.0  0.0
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  ...  0.0  0.0  11.0  16.0  10.0  0.0  0.0
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  ...  0.0  0.0   3.0  11.0  16.0  9.0  0.0
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  ...  0.0  7.0  13.0  13.0   9.0  0.0  0.0
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  ...  0.0  0.0   2.0  16.0   4.0  0.0  0.0

[5 rows x 64 columns]

In [19]:
df['target']=digits.target
df.head(20)

0    1     2     3     4     5  ...    59    60    61    62   63  target
0  0.0  0.0   5.0  13.0   9.0   1.0  ...  13.0  10.0   0.0   0.0  0.0       0
1  0.0  0.0   0.0  12.0  13.0   5.0  ...  11.0  16.0  10.0   0.0  0.0       1
2  0.0  0.0   0.0   4.0  15.0  12.0  ...   3.0  11.0  16.0   9.0  0.0       2
3  0.0  0.0   7.0  15.0  13.0   1.0  ...  13.0  13.0   9.0   0.0  0.0       3
4  0.0  0.0   0.0   1.0  11.0   0.0  ...   2.0  16.0   4.0   0.0  0.0       4
5  0.0  0.0  12.0  10.0   0.0   0.0  ...  16.0  16.0  10.0   0.0  0.0       5
6  0.0  0.0   0.0  12.0  13.0   0.0  ...   9.0  15.0  11.0   3.0  0.0       6
7  0.0  0.0   7.0   8.0  13.0  16.0  ...   5.0   0.0   0.0   0.0  0.0       7
8  0.0  0.0   9.0  14.0   8.0   1.0  ...  16.0  15.0  11.0   1.0  0.0       8
9  0.0  0.0  11.0  12.0   0.0   0.0  ...  12.0  13.0   3.0   0.0  0.0       9
0  0.0  0.0   1.0   9.0  15.0  11.0  ...  10.0  13.0   3.0   0.0  0.0       0
1  0.0  0.0   0.0   0.0  14.0  13.0  ...   1.0  13.0  16.0   1.0  0.0       1
2  0.0  0.0   5.0  12.0   1.0   0.0  ...  11.0   8.0  13.0  12.0  4.0       2
3  0.0  2.0   9.0  15.0  14.0   9.0  ...  12.0  13.0  11.0   0.0  0.0       3
4  0.0  0.0   0.0   8.0  15.0   1.0  ...  10.0  15.0   4.0   0.0  0.0       4
5  0.0  5.0  12.0  13.0  16.0  16.0  ...  16.0   2.0   0.0   0.0  0.0       5
6  0.0  0.0   0.0   8.0  15.0   1.0  ...   7.0  15.0  16.0  11.0  0.0       6
7  0.0  0.0   1.0   8.0  15.0  10.0  ...  11.0   9.0   0.0   0.0  0.0       7
8  0.0  0.0  10.0   7.0  13.0   9.0  ...  14.0   5.0   0.0   0.0  0.0       8
9  0.0  0.0   6.0  14.0   4.0   0.0  ...  16.0  16.0  13.0  11.0  1.0       9

[20 rows x 65 columns]

In [20]:
x = df.drop(['target'],axis='columns')
y=df['target']

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [22]:
from sklearn.svm import  SVC
model = SVC()

In [23]:
model.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [24]:
model.predict(x_test)

array([2, 9, 8, 8, 7, 0, 5, 6, 3, 9, 5, 5, 1, 7, 2, 3, 7, 2, 4, 7, 0, 1,
       4, 3, 5, 0, 7, 6, 5, 1, 9, 2, 6, 1, 8, 6, 3, 3, 6, 2, 0, 7, 8, 6,
       8, 0, 4, 3, 5, 8, 7, 9, 1, 1, 6, 2, 9, 7, 3, 7, 1, 8, 1, 4, 9, 2,
       6, 4, 2, 2, 3, 9, 0, 9, 8, 8, 2, 8, 3, 5, 4, 7, 4, 1, 9, 4, 7, 9,
       3, 2, 5, 7, 7, 6, 0, 9, 4, 3, 0, 5, 0, 6, 8, 6, 5, 2, 6, 8, 8, 1,
       3, 9, 5, 7, 6, 2, 5, 8, 6, 1, 3, 3, 2, 9, 5, 2, 2, 6, 7, 6, 3, 1,
       3, 5, 4, 2, 7, 6, 9, 2, 1, 6, 7, 5, 6, 4, 5, 0, 9, 1, 5, 6, 5, 1,
       1, 4, 8, 6, 9, 4, 5, 8, 6, 1, 0, 4, 5, 1, 4, 2, 3, 6, 2, 0, 4, 3,
       8, 8, 2, 5, 3, 3, 2, 9, 4, 7, 4, 9, 8, 5, 9, 7, 7, 0, 9, 3, 5, 9,
       8, 0, 2, 9, 6, 5, 5, 4, 5, 4, 9, 9, 8, 7, 9, 7, 7, 4, 3, 3, 1, 7,
       5, 8, 4, 5, 2, 8, 2, 3, 3, 9, 3, 8, 6, 1, 5, 0, 0, 4, 6, 7, 3, 2,
       7, 8, 6, 4, 9, 7, 1, 6, 1, 6, 7, 5, 7, 0, 3, 9, 5, 2, 0, 1, 8, 6,
       6, 9, 8, 9, 2, 5, 6, 7, 0, 5, 0, 3, 4, 1, 4, 8, 5, 2, 0, 9, 4, 0,
       6, 5, 2, 1, 5, 6, 0, 9, 0, 8, 5, 3, 8, 1, 1,

In [25]:
model.score(x_test,y_test)

0.9833333333333333

In [29]:
model1=SVC(kernel='rbf')
model1.fit(x_train,y_train)
model1.score(x_test,y_test)

0.9833333333333333

In [32]:
model2=SVC(kernel='linear')
model2.fit(x_train,y_train)
model2.score(x_test,y_test)

0.9777777777777777